apiVersion: v1
kind: Service
metadata:
  labels:
    app: crawlers
  name: crawlers
spec:
  ports:
  - name: "http"
    port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    app: crawlers
  type: NodePort
