apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/tech-docs-408301/docs/production
        name: docs
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: HTTP_PORT
            value: '8011'
          - name: TCP_PORT
            value: '8012'
        ports:
          - containerPort: 8011
          - containerPort: 8012


