apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs
  name: docs-http
spec:
  ports:
  - name: "http"
    port: 8011
    protocol: TCP
    targetPort: 8011
  selector:
    app: docs
  type: NodePort
